# Generated by Django 5.0.6 on 2024-06-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('REPTIL', 'Reptil'), ('AVE', 'Ave'), ('OTRO', 'Otro'), ('ROEDOR', 'Roedor'), ('GATO', 'Gato'), ('PERRO', 'Perro')], max_length=20),
        ),
    ]
