# Generated by Django 5.0.6 on 2024-05-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.PROTECT, to='crud.persona'),
        ),
    ]
