# Generated by Django 5.0.6 on 2024-05-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_mascota_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('ROEDOR', 'Roedor'), ('OTRO', 'Otro'), ('REPTIL', 'Reptil'), ('GATO', 'Gato'), ('PERRO', 'Perro'), ('AVE', 'Ave')], max_length=20),
        ),
    ]
