# Generated by Django 5.0.6 on 2024-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_mascota_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='subtipo',
            field=models.CharField(choices=[('Perro', [('CHICO', 'Chico'), ('VERDE', 'Verde'), ('GRANDE', 'Grande')]), ('Gato', [('ANGORA', 'Angora'), ('VOLADOR', 'Volador')]), ('REPTIL', [('ANACONDA', 'Anaconda'), ('LAGARTIJA', 'Lagartija')]), ('OTRO', 'otro')], default='OTRO', max_length=15),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('ROEDOR', 'Roedor'), ('AVE', 'Ave'), ('REPTIL', 'Reptil'), ('GATO', 'Gato'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
