# Generated by Django 5.0.6 on 2024-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_mascota_subtipo_alter_mascota_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(null=True, upload_to='personas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('REPTIL', 'Reptil'), ('OTRO', 'Otro'), ('AVE', 'Ave'), ('PERRO', 'Perro'), ('ROEDOR', 'Roedor'), ('GATO', 'Gato')], max_length=20),
        ),
    ]
